### PR TITLE
fixing valid amp doc regexp and increasing unversion files lifeline

### LINKED ISSUE #13: Increase cache duration for unversioned files to 7 days
Unversioned js files like `https://cdn.ampproject.org/v0.js` are cached for 5 minutes and deployed every seven days. We keep this cache age low so that we can quickly deploy a fix if we happen to ship any.
But in AMP-service worker we serve these files with a `staleWhileRevalidate` strategy which means if a user lands on a buggy version, he will still get the same buggy version next time but will be fixed on the third time.

We wanted to keep this number low initially so that we don't get stuck to this situation for a long time. 

But this might not be the best UX as many web apps are visited after a gap of one day and might have to download the scripts before serving to the page even if the scripts did not change.
With current defaults this can happen upto ~6 times a week for the user. So a better UX would be  to the AMPs release schedule instead and let the scripts update in background.

### PR DESCRIPTION
**Pull request by prateekbh**
- Fixes #13 
- Adds a better regexp for checking valid amp pages

### CODE REVIEW

File: src/modules/document-caching/AmpDocumentCachablePlugin.ts [hunk 1]
```diff
@@ -33,7 +33,7 @@ export default class AmpDocumentCachablePlugin extends Plugin {
       try {
         const responseBody = await clonedResponse.text();
         // Check if the response is AMP HTML page, only then cache it.
-        if (/<html (⚡|amphtml)/.test(responseBody)) {
+        if (/<html.*(\s)(⚡|amp)(\s.*>|>).*/.test(responseBody)) {
```
Comment (westonruter) [inline src/modules/document-caching/AmpDocumentCachablePlugin.ts]: Instead of `.*` I think this should be `[^>]*` as we don't want it to match outside of the start tag.

```suggestion
        if (/<html\s[^>]*(⚡|amp)[^>]*>/.test(responseBody)) {
```

Comment (prateekbh) [reply src/modules/document-caching/AmpDocumentCachablePlugin.ts]: Thanks :)

**Comment by prateekbh** [comment]
Should've merged this the other day
